version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - MYSQL_SERVER_NAME=db
      - MYSQL_SERVER_USER_NAME=root
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=cdrdb
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_SERVER_NAME: db
      MYSQL_SERVER_USER_NAME: root
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: cdrdb
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Database/database.sql:/docker-entrypoint-initdb.d/database.sql:ro
volumes:
  db_data:
